name: Release

on:
  push:
    branches:
      - 1.x
      - 1.x-release-workflow

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          package-name: ${{ github.event.client_payload.repo_name }}
          pull-request-header: ''
