name: Timmy tests

on:
  push:
    branches:
      - '1.x'
      - '2.x'
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

# Cancel previous workflow run groups that have not completed.
concurrency:
  # Group workflow runs by workflow name, along with the head branch ref of the pull request
  # or otherwise the branch or tag ref.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: timmy_test
        ports:
          - 3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
        wp: ['6.5', 'latest']
        multisite: ['0', '1']
        dependency-version: [prefer-stable] # prefer-lowest
        webp: [false]
        coverage: [false]
        extensions: ['gd']
        experimental: [false]
        include:
          # PHP 8.2
          - php: '8.2'
            wp: 'latest'
            dependency-version: 'prefer-stable'
            multisite: '0'
            experimental: false
          # PHP 8.3
          - php: '8.3'
            wp: 'latest'
            dependency-version: 'prefer-stable'
            multisite: '0'
            experimental: false
          # WP Trunk
          - php: '8.3'
            wp: 'trunk'
            dependency-version: 'prefer-stable'
            multisite: '0'
            experimental: true
          # PHP with Imagick
          - php: '8.3'
            wp: 'latest'
            dependency-version: 'prefer-stable'
            multisite: '0'
            extensions: 'imagick'
            experimental: false
          # PHP 8.4
          - php: '8.4'
            wp: 'latest'
            dependency-version: 'prefer-stable'
            multisite: '0'
            experimental: false
          # Coverage
          - php: '8.3'
            wp: 'latest'
            dependency-version: 'prefer-stable'
            multisite: '0'
            coverage: true
            experimental: false

    name: PHP ${{ matrix.php }} ${{ matrix.extensions == 'imagick' && ' (Imagick)' || '' }}${{ matrix.coverage && ' (with coverage)' || '' }} ${{ matrix.webp && ' (webp)' || '' }} | WP ${{ matrix.wp }}${{ matrix.multisite == 1 && ' (MS)' || '' }} | ${{ matrix.dependency-version }}

    steps:
      - uses: actions/checkout@v5

      - name: Install Subversion
        run: |
          sudo apt-get install -y subversion
          sudo apt-get update

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage && 'pcov' || 'none' }}
          tools: composer:v2
          extensions: curl, date, dom, iconv, json, libxml, mysql, ${{ matrix.extensions }}
          ini-values: pcov.directory=src

      - name: Shutdown default MySQL service
        run: sudo service mysql stop

      - name: Verify MariaDB connection
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"${{ job.services.mysql.ports[3306] }}" --silent; do
            sleep 1
          done

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependency-version }}

      - name: Install tests
        run: bash bin/install-wp-tests.sh timmy_test root '' 127.0.0.1:${{ job.services.mysql.ports['3306'] }} ${{ matrix.wp }} true

      - name: Run tests
        if: ${{ !matrix.webp }}
        run: composer run test:no-cov
        env:
          WP_MULTISITE: ${{ matrix.multisite }}

      - name: Run webp tests
        if: ${{ matrix.webp }}
        run: vendor/phpunit/phpunit/phpunit -c phpunit.xml --verbose --filter 'TestTimberImageToWEBP'
